#!/usr/bin/env bash
# MINITAGE POST UPDATE HOOK
cwd=$PWD
REPO_DIR=/git
REGEX_PART=""
for item in $(ls $REPO_DIR);do
    REGEX_PART="$item|$REGEX_PART"
done
TOP_REPOS_LIST=$(echo $REGEX_PART|sed -re "s/\|$//g")
if [ -f hooks/post-update ];then
    package=$(basename $PWD)
    output=$cwd/$package.tbz2
    [[ -d tmp ]] && rm -rf tmp
    git clone $cwd/ $cwd/tmp/ 2>&1>>/dev/null
    sed -re "s/url\s*=.*(($TOP_REPOS_LIST).*)/    url = ssh:\/\/git.minitage.org:682\/git\/\1/g" -i "$cwd/tmp/.git/config" 
    cd tmp
    tar cjpf $output .
    cd ..
    rm -rf tmp
    md5sum -b $output|awk '{print $1}'>$output.md5
    exec git update-server-info
fi

